language: elixir
elixir:
  - 1.4.2
  - 1.3.4
otp_release:
 - 19.2
 - 18.2.1
# Run in bigger container so we don't run out of memory generating the plt
sudo: required
cache:
  directories:
    - _build
    - deps
before_script:
  - MIX_ENV=test mix compile --warnings-as-errors
  - "if [ -z ${WALLABY_DRIVER} ]; then travis_wait mix dialyzer --plt; fi"
  - bash $TRAVIS_BUILD_DIR/test/tools/start_webdriver.sh

script:
  - mix test
  - "if [ -z ${WALLABY_DRIVER} ]; then mix dialyzer --halt-exit-status; fi"

matrix:
  exclude:
    - elixir: 1.4.2
      otp_release: 18.2.1
    - elixir: 1.3.4
      otp_release: 19.2

env:
  - ""
  - WALLABY_DRIVER=phantom
  - WALLABY_DRIVER=selenium WALLABY_SELENIUM_VERSION=3
  - WALLABY_DRIVER=selenium WALLABY_SELENIUM_VERSION=2

before_install:
  - "export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"
