language: elixir
elixir:
  - 1.8.2
  - 1.9.1
otp_release:
  - 21.3
  - 22.0
env:
  - ""
  - WALLABY_DRIVER=phantom
  - WALLABY_DRIVER=chrome
  - WALLABY_DRIVER=selenium
matrix:
  exclude:
  - elixir: 1.8.2
    otp_release: 22.0
  - elixir: 1.9.1
    otp_release: 21.3
# Run in bigger container so we don't run out of memory generating the plt
sudo: required
cache:
  directories:
    - _build
    - deps

dist: trusty

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo chmod +x chromedriver
  - sudo mv chromedriver /usr/local/bin
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo apt-get update
  - sudo apt-get --only-upgrade install google-chrome-stable
  - sudo apt-get install libstdc++6-4.7-dev
  - MIX_ENV=test mix compile --warnings-as-errors
  - if [ -z ${WALLABY_DRIVER} ]; then travis_wait mix dialyzer --plt; fi # only run dialyzer for the env without drivers
  - bash $TRAVIS_BUILD_DIR/test/tools/start_webdriver.sh

script:
  - mix coveralls.safe_travis
  - if [ -z ${WALLABY_DRIVER} ]; then mix dialyzer --halt-exit-status; fi # only run dialyzer for the env without drivers
  - mix credo --strict

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report

before_install:
  - "export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"
