name: Inch CI
on: 
  push:
    branches: master

jobs:
  inch:
    runs-on: ubuntu-latest
    name: Inch CI

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-elixir@v1.0.0
      with:
        otp-version: 21.x
        elixir-version: 1.9.x
    - uses: actions/cache@v1
      id: cache
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      env:
        MIX_ENV: docs
      run: mix deps.get

    - name: Run Formatter
      env:
        MIX_ENV: docs
      run: mix inch.report
